services:
  - type: web
    name: express-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        value: "mongodb+srv://sona:sona@sona.fz2qfno.mongodb.net/menu"
